
const ADMIN_PERMISSION = 101
const BUSINESS_MANAGE_PERMISSION = 102
const USER_MANAGE_PERMISSION = 103
const WAREHOUSE_MANAGE_PERMISSION = 104

module.exports = {
  ADMIN_PERMISSION,
  BUSINESS_MANAGE_PERMISSION,
  USER_MANAGE_PERMISSION,
  WAREHOUSE_MANAGE_PERMISSION
};
